apiVersion: v1
kind: Service
metadata:
  name: tempconv-backend
  labels:
    app: tempconv-backend
spec:
  type: ClusterIP
  selector:
    app: tempconv-backend
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
    - name: grpcweb
      port: 8080
      targetPort: grpcweb

